# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 644f9eb38f7aa2cd2eca83c04275ae3dbb96845a3a7727d5b5ba2a71aed1a6435d50dfa3939d2fb4aeaccedcb4db9013e8324fe260c8bd9f6a2721080c21b432

test:
  secret_key_base: 02d585efc55cf90f24f2fe3298843b6170f5b7d4a9ef680dbb5f0158163a7b6b5653ebaaf89bf94dbf872bcc64fc449a6c90accb54715f60e259d6fc899fa9e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
